{% set name = "foxplainer" %}
{% set version = "0.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2a697d92ceee947c72fce79a7a7d637bf0df967ebdd0a9c011cbcecfcddc7609

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - poetry

  run:
    - anytree >=2.8.0
    - ipywidgets >=7.7.1
    - numpy >=1.23.2
    - pandas >=1.4.3
    - python >=3.8
    - scikit-learn >=1.1.2
    - six >=1.16.0

test:
  imports:
    - foxplainer

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "FoX: a Fo rmal eX plainer for JIT Defect Prediction"
  doc_url: https://foxplainer.readthedocs.io/en/latest/
  dev_url: https://github.com/trustablefox/foxplainer.git

extra:
  recipe-maintainers:
    - trustablefox
